// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lestine-Yan/irisImg/backend/ent/accesslog"
	"github.com/Lestine-Yan/irisImg/backend/ent/predicate"
)

// AccessLogUpdate is the builder for updating AccessLog entities.
type AccessLogUpdate struct {
	config
	hooks    []Hook
	mutation *AccessLogMutation
}

// Where appends a list predicates to the AccessLogUpdate builder.
func (_u *AccessLogUpdate) Where(ps ...predicate.AccessLog) *AccessLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLevel sets the "level" field.
func (_u *AccessLogUpdate) SetLevel(v accesslog.Level) *AccessLogUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableLevel(v *accesslog.Level) *AccessLogUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetEvent sets the "event" field.
func (_u *AccessLogUpdate) SetEvent(v string) *AccessLogUpdate {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableEvent(v *string) *AccessLogUpdate {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AccessLogUpdate) SetMethod(v string) *AccessLogUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableMethod(v *string) *AccessLogUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *AccessLogUpdate) ClearMethod() *AccessLogUpdate {
	_u.mutation.ClearMethod()
	return _u
}

// SetPath sets the "path" field.
func (_u *AccessLogUpdate) SetPath(v string) *AccessLogUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillablePath(v *string) *AccessLogUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *AccessLogUpdate) ClearPath() *AccessLogUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccessLogUpdate) SetStatus(v int) *AccessLogUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableStatus(v *int) *AccessLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AccessLogUpdate) AddStatus(v int) *AccessLogUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *AccessLogUpdate) ClearStatus() *AccessLogUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AccessLogUpdate) SetDurationMs(v int) *AccessLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableDurationMs(v *int) *AccessLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AccessLogUpdate) AddDurationMs(v int) *AccessLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AccessLogUpdate) ClearDurationMs() *AccessLogUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *AccessLogUpdate) SetClientIP(v string) *AccessLogUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableClientIP(v *string) *AccessLogUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *AccessLogUpdate) ClearClientIP() *AccessLogUpdate {
	_u.mutation.ClearClientIP()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AccessLogUpdate) SetRequestID(v string) *AccessLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableRequestID(v *string) *AccessLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AccessLogUpdate) ClearRequestID() *AccessLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AccessLogUpdate) SetAPIKeyID(v int) *AccessLogUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableAPIKeyID(v *int) *AccessLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AccessLogUpdate) AddAPIKeyID(v int) *AccessLogUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *AccessLogUpdate) ClearAPIKeyID() *AccessLogUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *AccessLogUpdate) SetUsername(v string) *AccessLogUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableUsername(v *string) *AccessLogUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *AccessLogUpdate) ClearUsername() *AccessLogUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetMessage sets the "message" field.
func (_u *AccessLogUpdate) SetMessage(v string) *AccessLogUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableMessage(v *string) *AccessLogUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AccessLogUpdate) SetCreatedAt(v time.Time) *AccessLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AccessLogUpdate) SetNillableCreatedAt(v *time.Time) *AccessLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AccessLogMutation object of the builder.
func (_u *AccessLogUpdate) Mutation() *AccessLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccessLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccessLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessLogUpdate) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := accesslog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "AccessLog.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Event(); ok {
		if err := accesslog.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "AccessLog.event": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accesslog.Table, accesslog.Columns, sqlgraph.NewFieldSpec(accesslog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(accesslog.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(accesslog.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(accesslog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(accesslog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(accesslog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(accesslog.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accesslog.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(accesslog.FieldStatus, field.TypeInt, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(accesslog.FieldStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(accesslog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(accesslog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(accesslog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(accesslog.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(accesslog.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(accesslog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(accesslog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(accesslog.FieldAPIKeyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(accesslog.FieldAPIKeyID, field.TypeInt, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(accesslog.FieldAPIKeyID, field.TypeInt)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(accesslog.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(accesslog.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(accesslog.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(accesslog.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesslog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccessLogUpdateOne is the builder for updating a single AccessLog entity.
type AccessLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessLogMutation
}

// SetLevel sets the "level" field.
func (_u *AccessLogUpdateOne) SetLevel(v accesslog.Level) *AccessLogUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableLevel(v *accesslog.Level) *AccessLogUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetEvent sets the "event" field.
func (_u *AccessLogUpdateOne) SetEvent(v string) *AccessLogUpdateOne {
	_u.mutation.SetEvent(v)
	return _u
}

// SetNillableEvent sets the "event" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableEvent(v *string) *AccessLogUpdateOne {
	if v != nil {
		_u.SetEvent(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AccessLogUpdateOne) SetMethod(v string) *AccessLogUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableMethod(v *string) *AccessLogUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// ClearMethod clears the value of the "method" field.
func (_u *AccessLogUpdateOne) ClearMethod() *AccessLogUpdateOne {
	_u.mutation.ClearMethod()
	return _u
}

// SetPath sets the "path" field.
func (_u *AccessLogUpdateOne) SetPath(v string) *AccessLogUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillablePath(v *string) *AccessLogUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *AccessLogUpdateOne) ClearPath() *AccessLogUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AccessLogUpdateOne) SetStatus(v int) *AccessLogUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableStatus(v *int) *AccessLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AccessLogUpdateOne) AddStatus(v int) *AccessLogUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *AccessLogUpdateOne) ClearStatus() *AccessLogUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AccessLogUpdateOne) SetDurationMs(v int) *AccessLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableDurationMs(v *int) *AccessLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AccessLogUpdateOne) AddDurationMs(v int) *AccessLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AccessLogUpdateOne) ClearDurationMs() *AccessLogUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *AccessLogUpdateOne) SetClientIP(v string) *AccessLogUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableClientIP(v *string) *AccessLogUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *AccessLogUpdateOne) ClearClientIP() *AccessLogUpdateOne {
	_u.mutation.ClearClientIP()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AccessLogUpdateOne) SetRequestID(v string) *AccessLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableRequestID(v *string) *AccessLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AccessLogUpdateOne) ClearRequestID() *AccessLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AccessLogUpdateOne) SetAPIKeyID(v int) *AccessLogUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableAPIKeyID(v *int) *AccessLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AccessLogUpdateOne) AddAPIKeyID(v int) *AccessLogUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *AccessLogUpdateOne) ClearAPIKeyID() *AccessLogUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetUsername sets the "username" field.
func (_u *AccessLogUpdateOne) SetUsername(v string) *AccessLogUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableUsername(v *string) *AccessLogUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *AccessLogUpdateOne) ClearUsername() *AccessLogUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetMessage sets the "message" field.
func (_u *AccessLogUpdateOne) SetMessage(v string) *AccessLogUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableMessage(v *string) *AccessLogUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AccessLogUpdateOne) SetCreatedAt(v time.Time) *AccessLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AccessLogUpdateOne) SetNillableCreatedAt(v *time.Time) *AccessLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AccessLogMutation object of the builder.
func (_u *AccessLogUpdateOne) Mutation() *AccessLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccessLogUpdate builder.
func (_u *AccessLogUpdateOne) Where(ps ...predicate.AccessLog) *AccessLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccessLogUpdateOne) Select(field string, fields ...string) *AccessLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccessLog entity.
func (_u *AccessLogUpdateOne) Save(ctx context.Context) (*AccessLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccessLogUpdateOne) SaveX(ctx context.Context) *AccessLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccessLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccessLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccessLogUpdateOne) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := accesslog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "AccessLog.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Event(); ok {
		if err := accesslog.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "AccessLog.event": %w`, err)}
		}
	}
	return nil
}

func (_u *AccessLogUpdateOne) sqlSave(ctx context.Context) (_node *AccessLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accesslog.Table, accesslog.Columns, sqlgraph.NewFieldSpec(accesslog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesslog.FieldID)
		for _, f := range fields {
			if !accesslog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accesslog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(accesslog.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Event(); ok {
		_spec.SetField(accesslog.FieldEvent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(accesslog.FieldMethod, field.TypeString, value)
	}
	if _u.mutation.MethodCleared() {
		_spec.ClearField(accesslog.FieldMethod, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(accesslog.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(accesslog.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(accesslog.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(accesslog.FieldStatus, field.TypeInt, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(accesslog.FieldStatus, field.TypeInt)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(accesslog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(accesslog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(accesslog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(accesslog.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(accesslog.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(accesslog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(accesslog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(accesslog.FieldAPIKeyID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(accesslog.FieldAPIKeyID, field.TypeInt, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(accesslog.FieldAPIKeyID, field.TypeInt)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(accesslog.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(accesslog.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(accesslog.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(accesslog.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &AccessLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesslog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
