// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lestine-Yan/irisImg/backend/ent/accesslog"
)

// AccessLogCreate is the builder for creating a AccessLog entity.
type AccessLogCreate struct {
	config
	mutation *AccessLogMutation
	hooks    []Hook
}

// SetTimestamp sets the "timestamp" field.
func (_c *AccessLogCreate) SetTimestamp(v time.Time) *AccessLogCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableTimestamp(v *time.Time) *AccessLogCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetLevel sets the "level" field.
func (_c *AccessLogCreate) SetLevel(v accesslog.Level) *AccessLogCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableLevel(v *accesslog.Level) *AccessLogCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetEvent sets the "event" field.
func (_c *AccessLogCreate) SetEvent(v string) *AccessLogCreate {
	_c.mutation.SetEvent(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *AccessLogCreate) SetMethod(v string) *AccessLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableMethod(v *string) *AccessLogCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *AccessLogCreate) SetPath(v string) *AccessLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillablePath(v *string) *AccessLogCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccessLogCreate) SetStatus(v int) *AccessLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableStatus(v *int) *AccessLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AccessLogCreate) SetDurationMs(v int) *AccessLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableDurationMs(v *int) *AccessLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *AccessLogCreate) SetClientIP(v string) *AccessLogCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableClientIP(v *string) *AccessLogCreate {
	if v != nil {
		_c.SetClientIP(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *AccessLogCreate) SetRequestID(v string) *AccessLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableRequestID(v *string) *AccessLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *AccessLogCreate) SetAPIKeyID(v int) *AccessLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableAPIKeyID(v *int) *AccessLogCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *AccessLogCreate) SetUsername(v string) *AccessLogCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableUsername(v *string) *AccessLogCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *AccessLogCreate) SetMessage(v string) *AccessLogCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableMessage(v *string) *AccessLogCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccessLogCreate) SetCreatedAt(v time.Time) *AccessLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccessLogCreate) SetNillableCreatedAt(v *time.Time) *AccessLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AccessLogMutation object of the builder.
func (_c *AccessLogCreate) Mutation() *AccessLogMutation {
	return _c.mutation
}

// Save creates the AccessLog in the database.
func (_c *AccessLogCreate) Save(ctx context.Context) (*AccessLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessLogCreate) SaveX(ctx context.Context) *AccessLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessLogCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := accesslog.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.Level(); !ok {
		v := accesslog.DefaultLevel
		_c.mutation.SetLevel(v)
	}
	if _, ok := _c.mutation.Message(); !ok {
		v := accesslog.DefaultMessage
		_c.mutation.SetMessage(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accesslog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessLogCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AccessLog.timestamp"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "AccessLog.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := accesslog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "AccessLog.level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Event(); !ok {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required field "AccessLog.event"`)}
	}
	if v, ok := _c.mutation.Event(); ok {
		if err := accesslog.EventValidator(v); err != nil {
			return &ValidationError{Name: "event", err: fmt.Errorf(`ent: validator failed for field "AccessLog.event": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "AccessLog.message"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessLog.created_at"`)}
	}
	return nil
}

func (_c *AccessLogCreate) sqlSave(ctx context.Context) (*AccessLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessLogCreate) createSpec() (*AccessLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accesslog.Table, sqlgraph.NewFieldSpec(accesslog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(accesslog.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(accesslog.FieldLevel, field.TypeEnum, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Event(); ok {
		_spec.SetField(accesslog.FieldEvent, field.TypeString, value)
		_node.Event = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(accesslog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(accesslog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accesslog.FieldStatus, field.TypeInt, value)
		_node.Status = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(accesslog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(accesslog.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(accesslog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(accesslog.FieldAPIKeyID, field.TypeInt, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(accesslog.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(accesslog.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accesslog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AccessLogCreateBulk is the builder for creating many AccessLog entities in bulk.
type AccessLogCreateBulk struct {
	config
	err      error
	builders []*AccessLogCreate
}

// Save creates the AccessLog entities in the database.
func (_c *AccessLogCreateBulk) Save(ctx context.Context) ([]*AccessLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessLogCreateBulk) SaveX(ctx context.Context) []*AccessLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
