// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Lestine-Yan/irisImg/backend/ent/accesslog"
)

// AccessLog is the model entity for the AccessLog schema.
type AccessLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 日志发生时间，用于排序 / 直方图 / 时间范围过滤
	Timestamp time.Time `json:"timestamp,omitempty"`
	// 日志级别
	Level accesslog.Level `json:"level,omitempty"`
	// 事件类型
	Event string `json:"event,omitempty"`
	// HTTP 方法，仅访问日志有值
	Method string `json:"method,omitempty"`
	// 请求路径，用于关键字模糊匹配
	Path string `json:"path,omitempty"`
	// HTTP 状态码，非请求类事件为空
	Status *int `json:"status,omitempty"`
	// 请求耗时（毫秒），仅访问日志有值
	DurationMs *int `json:"duration_ms,omitempty"`
	// 客户端 IP
	ClientIP string `json:"client_ip,omitempty"`
	// 请求追踪 ID，关联同一请求的访问日志与业务事件
	RequestID string `json:"request_id,omitempty"`
	// 来源 API 密钥 ID，无关联时为空
	APIKeyID *int `json:"api_key_id,omitempty"`
	// 操作者用户名（JWT 登录用户）
	Username string `json:"username,omitempty"`
	// 可读描述 / 错误信息
	Message string `json:"message,omitempty"`
	// 记录落库时间
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accesslog.FieldID, accesslog.FieldStatus, accesslog.FieldDurationMs, accesslog.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case accesslog.FieldLevel, accesslog.FieldEvent, accesslog.FieldMethod, accesslog.FieldPath, accesslog.FieldClientIP, accesslog.FieldRequestID, accesslog.FieldUsername, accesslog.FieldMessage:
			values[i] = new(sql.NullString)
		case accesslog.FieldTimestamp, accesslog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessLog fields.
func (_m *AccessLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accesslog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case accesslog.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case accesslog.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = accesslog.Level(value.String)
			}
		case accesslog.FieldEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event", values[i])
			} else if value.Valid {
				_m.Event = value.String
			}
		case accesslog.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case accesslog.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case accesslog.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = new(int)
				*_m.Status = int(value.Int64)
			}
		case accesslog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int)
				*_m.DurationMs = int(value.Int64)
			}
		case accesslog.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case accesslog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case accesslog.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int)
				*_m.APIKeyID = int(value.Int64)
			}
		case accesslog.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case accesslog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case accesslog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessLog.
// This includes values selected through modifiers, order, etc.
func (_m *AccessLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccessLog.
// Note that you need to call AccessLog.Unwrap() before calling this method if this AccessLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccessLog) Update() *AccessLogUpdateOne {
	return NewAccessLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccessLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccessLog) Unwrap() *AccessLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccessLog) String() string {
	var builder strings.Builder
	builder.WriteString("AccessLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("event=")
	builder.WriteString(_m.Event)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	if v := _m.Status; v != nil {
		builder.WriteString("status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccessLogs is a parsable slice of AccessLog.
type AccessLogs []*AccessLog
