// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lestine-Yan/irisImg/backend/ent/apikey"
	"github.com/Lestine-Yan/irisImg/backend/ent/image"
	"github.com/Lestine-Yan/irisImg/backend/ent/predicate"
)

// ApiKeyUpdate is the builder for updating ApiKey entities.
type ApiKeyUpdate struct {
	config
	hooks    []Hook
	mutation *ApiKeyMutation
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (_u *ApiKeyUpdate) Where(ps ...predicate.ApiKey) *ApiKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ApiKeyUpdate) SetName(v string) *ApiKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableName(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *ApiKeyUpdate) SetKeyHash(v string) *ApiKeyUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableKeyHash(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *ApiKeyUpdate) SetPrefix(v string) *ApiKeyUpdate {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillablePrefix(v *string) *ApiKeyUpdate {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *ApiKeyUpdate) SetScope(v apikey.Scope) *ApiKeyUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableScope(v *apikey.Scope) *ApiKeyUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetRateLimit sets the "rate_limit" field.
func (_u *ApiKeyUpdate) SetRateLimit(v int) *ApiKeyUpdate {
	_u.mutation.ResetRateLimit()
	_u.mutation.SetRateLimit(v)
	return _u
}

// SetNillableRateLimit sets the "rate_limit" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableRateLimit(v *int) *ApiKeyUpdate {
	if v != nil {
		_u.SetRateLimit(*v)
	}
	return _u
}

// AddRateLimit adds value to the "rate_limit" field.
func (_u *ApiKeyUpdate) AddRateLimit(v int) *ApiKeyUpdate {
	_u.mutation.AddRateLimit(v)
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *ApiKeyUpdate) SetRevoked(v bool) *ApiKeyUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableRevoked(v *bool) *ApiKeyUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ApiKeyUpdate) SetLastUsedAt(v time.Time) *ApiKeyUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ApiKeyUpdate) SetNillableLastUsedAt(v *time.Time) *ApiKeyUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ApiKeyUpdate) ClearLastUsedAt() *ApiKeyUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// AddImageIDs adds the "images" edge to the Image entity by IDs.
func (_u *ApiKeyUpdate) AddImageIDs(ids ...int) *ApiKeyUpdate {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the Image entity.
func (_u *ApiKeyUpdate) AddImages(v ...*Image) *ApiKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (_u *ApiKeyUpdate) Mutation() *ApiKeyMutation {
	return _u.mutation
}

// ClearImages clears all "images" edges to the Image entity.
func (_u *ApiKeyUpdate) ClearImages() *ApiKeyUpdate {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to Image entities by IDs.
func (_u *ApiKeyUpdate) RemoveImageIDs(ids ...int) *ApiKeyUpdate {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to Image entities.
func (_u *ApiKeyUpdate) RemoveImages(v ...*Image) *ApiKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiKeyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := apikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ApiKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := apikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prefix(); ok {
		if err := apikey.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "ApiKey.prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := apikey.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "ApiKey.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateLimit(); ok {
		if err := apikey.RateLimitValidator(v); err != nil {
			return &ValidationError{Name: "rate_limit", err: fmt.Errorf(`ent: validator failed for field "ApiKey.rate_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *ApiKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(apikey.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(apikey.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RateLimit(); ok {
		_spec.SetField(apikey.FieldRateLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimit(); ok {
		_spec.AddField(apikey.FieldRateLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(apikey.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apikey.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.ImagesTable,
			Columns: []string{apikey.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.ImagesTable,
			Columns: []string{apikey.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.ImagesTable,
			Columns: []string{apikey.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiKeyUpdateOne is the builder for updating a single ApiKey entity.
type ApiKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiKeyMutation
}

// SetName sets the "name" field.
func (_u *ApiKeyUpdateOne) SetName(v string) *ApiKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableName(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *ApiKeyUpdateOne) SetKeyHash(v string) *ApiKeyUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableKeyHash(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *ApiKeyUpdateOne) SetPrefix(v string) *ApiKeyUpdateOne {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillablePrefix(v *string) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *ApiKeyUpdateOne) SetScope(v apikey.Scope) *ApiKeyUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableScope(v *apikey.Scope) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetRateLimit sets the "rate_limit" field.
func (_u *ApiKeyUpdateOne) SetRateLimit(v int) *ApiKeyUpdateOne {
	_u.mutation.ResetRateLimit()
	_u.mutation.SetRateLimit(v)
	return _u
}

// SetNillableRateLimit sets the "rate_limit" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableRateLimit(v *int) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetRateLimit(*v)
	}
	return _u
}

// AddRateLimit adds value to the "rate_limit" field.
func (_u *ApiKeyUpdateOne) AddRateLimit(v int) *ApiKeyUpdateOne {
	_u.mutation.AddRateLimit(v)
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *ApiKeyUpdateOne) SetRevoked(v bool) *ApiKeyUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableRevoked(v *bool) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ApiKeyUpdateOne) SetLastUsedAt(v time.Time) *ApiKeyUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ApiKeyUpdateOne) SetNillableLastUsedAt(v *time.Time) *ApiKeyUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ApiKeyUpdateOne) ClearLastUsedAt() *ApiKeyUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// AddImageIDs adds the "images" edge to the Image entity by IDs.
func (_u *ApiKeyUpdateOne) AddImageIDs(ids ...int) *ApiKeyUpdateOne {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the Image entity.
func (_u *ApiKeyUpdateOne) AddImages(v ...*Image) *ApiKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// Mutation returns the ApiKeyMutation object of the builder.
func (_u *ApiKeyUpdateOne) Mutation() *ApiKeyMutation {
	return _u.mutation
}

// ClearImages clears all "images" edges to the Image entity.
func (_u *ApiKeyUpdateOne) ClearImages() *ApiKeyUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to Image entities by IDs.
func (_u *ApiKeyUpdateOne) RemoveImageIDs(ids ...int) *ApiKeyUpdateOne {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to Image entities.
func (_u *ApiKeyUpdateOne) RemoveImages(v ...*Image) *ApiKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// Where appends a list predicates to the ApiKeyUpdate builder.
func (_u *ApiKeyUpdateOne) Where(ps ...predicate.ApiKey) *ApiKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiKeyUpdateOne) Select(field string, fields ...string) *ApiKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiKey entity.
func (_u *ApiKeyUpdateOne) Save(ctx context.Context) (*ApiKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyUpdateOne) SaveX(ctx context.Context) *ApiKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := apikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ApiKey.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := apikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "ApiKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Prefix(); ok {
		if err := apikey.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "ApiKey.prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := apikey.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "ApiKey.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateLimit(); ok {
		if err := apikey.RateLimitValidator(v); err != nil {
			return &ValidationError{Name: "rate_limit", err: fmt.Errorf(`ent: validator failed for field "ApiKey.rate_limit": %w`, err)}
		}
	}
	return nil
}

func (_u *ApiKeyUpdateOne) sqlSave(ctx context.Context) (_node *ApiKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikey.FieldID)
		for _, f := range fields {
			if !apikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(apikey.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(apikey.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RateLimit(); ok {
		_spec.SetField(apikey.FieldRateLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimit(); ok {
		_spec.AddField(apikey.FieldRateLimit, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(apikey.FieldRevoked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apikey.FieldLastUsedAt, field.TypeTime)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.ImagesTable,
			Columns: []string{apikey.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.ImagesTable,
			Columns: []string{apikey.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   apikey.ImagesTable,
			Columns: []string{apikey.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
