// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lestine-Yan/irisImg/backend/ent/image"
	"github.com/Lestine-Yan/irisImg/backend/ent/predicate"
)

// ImageUpdate is the builder for updating Image entities.
type ImageUpdate struct {
	config
	hooks    []Hook
	mutation *ImageMutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (_u *ImageUpdate) Where(ps ...predicate.Image) *ImageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *ImageUpdate) SetFilename(v string) *ImageUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableFilename(v *string) *ImageUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetStoredPath sets the "stored_path" field.
func (_u *ImageUpdate) SetStoredPath(v string) *ImageUpdate {
	_u.mutation.SetStoredPath(v)
	return _u
}

// SetNillableStoredPath sets the "stored_path" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableStoredPath(v *string) *ImageUpdate {
	if v != nil {
		_u.SetStoredPath(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ImageUpdate) SetURL(v string) *ImageUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableURL(v *string) *ImageUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *ImageUpdate) SetSize(v int64) *ImageUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableSize(v *int64) *ImageUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *ImageUpdate) AddSize(v int64) *ImageUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageUpdate) SetMimeType(v string) *ImageUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableMimeType(v *string) *ImageUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageUpdate) SetWidth(v int) *ImageUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableWidth(v *int) *ImageUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageUpdate) AddWidth(v int) *ImageUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageUpdate) SetHeight(v int) *ImageUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableHeight(v *int) *ImageUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageUpdate) AddHeight(v int) *ImageUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *ImageUpdate) SetHash(v string) *ImageUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableHash(v *string) *ImageUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// Mutation returns the ImageMutation object of the builder.
func (_u *ImageUpdate) Mutation() *ImageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageUpdate) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := image.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Image.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoredPath(); ok {
		if err := image.StoredPathValidator(v); err != nil {
			return &ValidationError{Name: "stored_path", err: fmt.Errorf(`ent: validator failed for field "Image.stored_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := image.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Image.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := image.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "Image.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := image.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Image.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := image.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "Image.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := image.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "Image.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := image.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Image.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(image.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.StoredPath(); ok {
		_spec.SetField(image.FieldStoredPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(image.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(image.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(image.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(image.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(image.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(image.FieldHash, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageUpdateOne is the builder for updating a single Image entity.
type ImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageMutation
}

// SetFilename sets the "filename" field.
func (_u *ImageUpdateOne) SetFilename(v string) *ImageUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableFilename(v *string) *ImageUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetStoredPath sets the "stored_path" field.
func (_u *ImageUpdateOne) SetStoredPath(v string) *ImageUpdateOne {
	_u.mutation.SetStoredPath(v)
	return _u
}

// SetNillableStoredPath sets the "stored_path" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableStoredPath(v *string) *ImageUpdateOne {
	if v != nil {
		_u.SetStoredPath(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ImageUpdateOne) SetURL(v string) *ImageUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableURL(v *string) *ImageUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *ImageUpdateOne) SetSize(v int64) *ImageUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableSize(v *int64) *ImageUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *ImageUpdateOne) AddSize(v int64) *ImageUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageUpdateOne) SetMimeType(v string) *ImageUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableMimeType(v *string) *ImageUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageUpdateOne) SetWidth(v int) *ImageUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableWidth(v *int) *ImageUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageUpdateOne) AddWidth(v int) *ImageUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageUpdateOne) SetHeight(v int) *ImageUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableHeight(v *int) *ImageUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageUpdateOne) AddHeight(v int) *ImageUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *ImageUpdateOne) SetHash(v string) *ImageUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableHash(v *string) *ImageUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// Mutation returns the ImageMutation object of the builder.
func (_u *ImageUpdateOne) Mutation() *ImageMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (_u *ImageUpdateOne) Where(ps ...predicate.Image) *ImageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageUpdateOne) Select(field string, fields ...string) *ImageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Image entity.
func (_u *ImageUpdateOne) Save(ctx context.Context) (*Image, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageUpdateOne) SaveX(ctx context.Context) *Image {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageUpdateOne) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := image.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Image.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoredPath(); ok {
		if err := image.StoredPathValidator(v); err != nil {
			return &ValidationError{Name: "stored_path", err: fmt.Errorf(`ent: validator failed for field "Image.stored_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := image.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Image.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := image.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "Image.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := image.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Image.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := image.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "Image.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := image.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "Image.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := image.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Image.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageUpdateOne) sqlSave(ctx context.Context) (_node *Image, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Image.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, image.FieldID)
		for _, f := range fields {
			if !image.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != image.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(image.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.StoredPath(); ok {
		_spec.SetField(image.FieldStoredPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(image.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(image.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(image.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(image.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(image.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(image.FieldHash, field.TypeString, value)
	}
	_node = &Image{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
