// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Lestine-Yan/irisImg/backend/ent/apikey"
	"github.com/Lestine-Yan/irisImg/backend/ent/image"
)

// ImageCreate is the builder for creating a Image entity.
type ImageCreate struct {
	config
	mutation *ImageMutation
	hooks    []Hook
}

// SetFilename sets the "filename" field.
func (_c *ImageCreate) SetFilename(v string) *ImageCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetStoredPath sets the "stored_path" field.
func (_c *ImageCreate) SetStoredPath(v string) *ImageCreate {
	_c.mutation.SetStoredPath(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *ImageCreate) SetURL(v string) *ImageCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *ImageCreate) SetSize(v int64) *ImageCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *ImageCreate) SetMimeType(v string) *ImageCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *ImageCreate) SetWidth(v int) *ImageCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *ImageCreate) SetNillableWidth(v *int) *ImageCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *ImageCreate) SetHeight(v int) *ImageCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *ImageCreate) SetNillableHeight(v *int) *ImageCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *ImageCreate) SetHash(v string) *ImageCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageCreate) SetCreatedAt(v time.Time) *ImageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageCreate) SetNillableCreatedAt(v *time.Time) *ImageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetKeyID sets the "key_id" field.
func (_c *ImageCreate) SetKeyID(v int) *ImageCreate {
	_c.mutation.SetKeyID(v)
	return _c
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_c *ImageCreate) SetNillableKeyID(v *int) *ImageCreate {
	if v != nil {
		_c.SetKeyID(*v)
	}
	return _c
}

// SetKey sets the "key" edge to the ApiKey entity.
func (_c *ImageCreate) SetKey(v *ApiKey) *ImageCreate {
	return _c.SetKeyID(v.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (_c *ImageCreate) Mutation() *ImageMutation {
	return _c.mutation
}

// Save creates the Image in the database.
func (_c *ImageCreate) Save(ctx context.Context) (*Image, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageCreate) SaveX(ctx context.Context) *Image {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageCreate) defaults() {
	if _, ok := _c.mutation.Width(); !ok {
		v := image.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := image.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := image.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageCreate) check() error {
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "Image.filename"`)}
	}
	if v, ok := _c.mutation.Filename(); ok {
		if err := image.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Image.filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StoredPath(); !ok {
		return &ValidationError{Name: "stored_path", err: errors.New(`ent: missing required field "Image.stored_path"`)}
	}
	if v, ok := _c.mutation.StoredPath(); ok {
		if err := image.StoredPathValidator(v); err != nil {
			return &ValidationError{Name: "stored_path", err: fmt.Errorf(`ent: validator failed for field "Image.stored_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Image.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := image.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Image.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Image.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := image.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "Image.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "Image.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := image.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Image.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "Image.width"`)}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := image.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "Image.width": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "Image.height"`)}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := image.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "Image.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "Image.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := image.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "Image.hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Image.created_at"`)}
	}
	return nil
}

func (_c *ImageCreate) sqlSave(ctx context.Context) (*Image, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageCreate) createSpec() (*Image, *sqlgraph.CreateSpec) {
	var (
		_node = &Image{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(image.Table, sqlgraph.NewFieldSpec(image.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(image.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.StoredPath(); ok {
		_spec.SetField(image.FieldStoredPath, field.TypeString, value)
		_node.StoredPath = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(image.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(image.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(image.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(image.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(image.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.KeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.KeyTable,
			Columns: []string{image.KeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.KeyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ImageCreateBulk is the builder for creating many Image entities in bulk.
type ImageCreateBulk struct {
	config
	err      error
	builders []*ImageCreate
}

// Save creates the Image entities in the database.
func (_c *ImageCreateBulk) Save(ctx context.Context) ([]*Image, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Image, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageCreateBulk) SaveX(ctx context.Context) []*Image {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
