// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Lestine-Yan/irisImg/backend/ent/apikey"
	"github.com/Lestine-Yan/irisImg/backend/ent/image"
	"github.com/Lestine-Yan/irisImg/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[0].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = apikeyDescName.Validators[0].(func(string) error)
	// apikeyDescKeyHash is the schema descriptor for key_hash field.
	apikeyDescKeyHash := apikeyFields[1].Descriptor()
	// apikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	apikey.KeyHashValidator = apikeyDescKeyHash.Validators[0].(func(string) error)
	// apikeyDescPrefix is the schema descriptor for prefix field.
	apikeyDescPrefix := apikeyFields[2].Descriptor()
	// apikey.PrefixValidator is a validator for the "prefix" field. It is called by the builders before save.
	apikey.PrefixValidator = apikeyDescPrefix.Validators[0].(func(string) error)
	// apikeyDescRateLimit is the schema descriptor for rate_limit field.
	apikeyDescRateLimit := apikeyFields[4].Descriptor()
	// apikey.DefaultRateLimit holds the default value on creation for the rate_limit field.
	apikey.DefaultRateLimit = apikeyDescRateLimit.Default.(int)
	// apikey.RateLimitValidator is a validator for the "rate_limit" field. It is called by the builders before save.
	apikey.RateLimitValidator = apikeyDescRateLimit.Validators[0].(func(int) error)
	// apikeyDescRevoked is the schema descriptor for revoked field.
	apikeyDescRevoked := apikeyFields[5].Descriptor()
	// apikey.DefaultRevoked holds the default value on creation for the revoked field.
	apikey.DefaultRevoked = apikeyDescRevoked.Default.(bool)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[7].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescFilename is the schema descriptor for filename field.
	imageDescFilename := imageFields[0].Descriptor()
	// image.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	image.FilenameValidator = imageDescFilename.Validators[0].(func(string) error)
	// imageDescStoredPath is the schema descriptor for stored_path field.
	imageDescStoredPath := imageFields[1].Descriptor()
	// image.StoredPathValidator is a validator for the "stored_path" field. It is called by the builders before save.
	image.StoredPathValidator = imageDescStoredPath.Validators[0].(func(string) error)
	// imageDescURL is the schema descriptor for url field.
	imageDescURL := imageFields[2].Descriptor()
	// image.URLValidator is a validator for the "url" field. It is called by the builders before save.
	image.URLValidator = imageDescURL.Validators[0].(func(string) error)
	// imageDescSize is the schema descriptor for size field.
	imageDescSize := imageFields[3].Descriptor()
	// image.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	image.SizeValidator = imageDescSize.Validators[0].(func(int64) error)
	// imageDescMimeType is the schema descriptor for mime_type field.
	imageDescMimeType := imageFields[4].Descriptor()
	// image.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	image.MimeTypeValidator = imageDescMimeType.Validators[0].(func(string) error)
	// imageDescWidth is the schema descriptor for width field.
	imageDescWidth := imageFields[5].Descriptor()
	// image.DefaultWidth holds the default value on creation for the width field.
	image.DefaultWidth = imageDescWidth.Default.(int)
	// image.WidthValidator is a validator for the "width" field. It is called by the builders before save.
	image.WidthValidator = imageDescWidth.Validators[0].(func(int) error)
	// imageDescHeight is the schema descriptor for height field.
	imageDescHeight := imageFields[6].Descriptor()
	// image.DefaultHeight holds the default value on creation for the height field.
	image.DefaultHeight = imageDescHeight.Default.(int)
	// image.HeightValidator is a validator for the "height" field. It is called by the builders before save.
	image.HeightValidator = imageDescHeight.Validators[0].(func(int) error)
	// imageDescHash is the schema descriptor for hash field.
	imageDescHash := imageFields[7].Descriptor()
	// image.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	image.HashValidator = imageDescHash.Validators[0].(func(string) error)
	// imageDescCreatedAt is the schema descriptor for created_at field.
	imageDescCreatedAt := imageFields[8].Descriptor()
	// image.DefaultCreatedAt holds the default value on creation for the created_at field.
	image.DefaultCreatedAt = imageDescCreatedAt.Default.(func() time.Time)
}
