// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LogsColumns holds the columns for the "logs" table.
	LogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "level", Type: field.TypeEnum, Enums: []string{"debug", "info", "warn", "error"}, Default: "info"},
		{Name: "event", Type: field.TypeString},
		{Name: "method", Type: field.TypeString, Nullable: true},
		{Name: "path", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "client_ip", Type: field.TypeString, Nullable: true},
		{Name: "request_id", Type: field.TypeString, Nullable: true},
		{Name: "api_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "message", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LogsTable holds the schema information for the "logs" table.
	LogsTable = &schema.Table{
		Name:       "logs",
		Columns:    LogsColumns,
		PrimaryKey: []*schema.Column{LogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accesslog_timestamp",
				Unique:  false,
				Columns: []*schema.Column{LogsColumns[1]},
			},
			{
				Name:    "accesslog_level",
				Unique:  false,
				Columns: []*schema.Column{LogsColumns[2]},
			},
			{
				Name:    "accesslog_event",
				Unique:  false,
				Columns: []*schema.Column{LogsColumns[3]},
			},
			{
				Name:    "accesslog_request_id",
				Unique:  false,
				Columns: []*schema.Column{LogsColumns[9]},
			},
			{
				Name:    "accesslog_api_key_id",
				Unique:  false,
				Columns: []*schema.Column{LogsColumns[10]},
			},
		},
	}
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "key_hash", Type: field.TypeString, Unique: true},
		{Name: "prefix", Type: field.TypeString},
		{Name: "scope", Type: field.TypeEnum, Enums: []string{"readonly", "readwrite"}},
		{Name: "rate_limit", Type: field.TypeInt, Default: 0},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_key_hash",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[2]},
			},
		},
	}
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "filename", Type: field.TypeString},
		{Name: "stored_path", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "width", Type: field.TypeInt, Default: 0},
		{Name: "height", Type: field.TypeInt, Default: 0},
		{Name: "hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "key_id", Type: field.TypeInt, Nullable: true},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "images_api_keys_images",
				Columns:    []*schema.Column{ImagesColumns[10]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "image_hash",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[8]},
			},
			{
				Name:    "image_created_at",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LogsTable,
		APIKeysTable,
		ImagesTable,
	}
)

func init() {
	LogsTable.Annotation = &entsql.Annotation{
		Table: "logs",
	}
	ImagesTable.ForeignKeys[0].RefTable = APIKeysTable
}
