// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "filename", Type: field.TypeString},
		{Name: "stored_path", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "width", Type: field.TypeInt, Default: 0},
		{Name: "height", Type: field.TypeInt, Default: 0},
		{Name: "hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "image_hash",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[8]},
			},
			{
				Name:    "image_created_at",
				Unique:  false,
				Columns: []*schema.Column{ImagesColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ImagesTable,
	}
)

func init() {
}
